### PR TITLE
Add permission checks against VaMa services

### PR DESCRIPTION
**Pull request by vangual**
Will also enable to check if a given person is allowed to work on a service

### CODE REVIEW

**Comment by vangual** [comment]
Do **NOT** merge this yet, but you can work alongside the changes

**Comment by vangual** [comment]
This may now be reviewed. It's working so far on my DWP instance.

**Comment by vangual** [comment]
**To reduce any potential downtimes, I'll merge it myself once the reviews are in.**

**Review by matal0 — APPROVED** [review]
lgtm

**Pull request merged**
